version: "2"
services:
  taxadata:
    build: .
    volumes:
      - .:/var/www/
    environment:
      ELASTICSEARCH: http://elasticsearch:9200
      INDEX: dwc
  elasticsearch:
    image: diogok/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - /var/data/dwc-elasticsearch/data:/usr/share/elasticsearch/data:rw
  kibana:
    image: diogok/kibana
    ports:
      - 8001:8001
